// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTSnEvXAUU8vkt2dk2XZlIrhZx2-QtpwA',
    appId: '1:1049226047630:web:99899c50d626b2b03b59df',
    messagingSenderId: '1049226047630',
    projectId: 'gino-923bb',
    authDomain: 'gino-923bb.firebaseapp.com',
    storageBucket: 'gino-923bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs-_RQOqJiBY45DleGGqNSloIOVHDQOrc',
    appId: '1:1049226047630:android:1013fe66571cd26f3b59df',
    messagingSenderId: '1049226047630',
    projectId: 'gino-923bb',
    storageBucket: 'gino-923bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw0rJfN_ZXE2WGXbwuVuARkJdQW_xHD2k',
    appId: '1:894004314968:ios:7d53bfb845198bab8ddb2d',
    messagingSenderId: '894004314968',
    projectId: 'gino',
    storageBucket: 'gino.firebasestorage.app',
    iosBundleId: 'com.example.huit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw0rJfN_ZXE2WGXbwuVuARkJdQW_xHD2k',
    appId: '1:894004314968:ios:7d53bfb845198bab8ddb2d',
    messagingSenderId: '894004314968',
    projectId: 'gino',
    storageBucket: 'gino.firebasestorage.app',
    iosBundleId: 'com.example.huit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTSnEvXAUU8vkt2dk2XZlIrhZx2-QtpwA',
    appId: '1:1049226047630:web:99899c50d626b2b03b59df',
    messagingSenderId: '1049226047630',
    projectId: 'gino-923bb',
    authDomain: 'gino-923bb.firebaseapp.com',
    storageBucket: 'gino-923bb.firebasestorage.app',
  );

}