// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsgBrxqgSCt83BxDHQyeScSAVRj7pwK7s',
    appId: '1:894004314968:web:27109f9dc09e72758ddb2d',
    messagingSenderId: '894004314968',
    projectId: 'huit-americain',
    authDomain: 'huit-americain.firebaseapp.com',
    storageBucket: 'huit-americain.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxybey_rOE3REyIJxZFbDmxoKvSLG2OAQ',
    appId: '1:894004314968:android:ac177d33d22c02688ddb2d',
    messagingSenderId: '894004314968',
    projectId: 'huit-americain',
    storageBucket: 'huit-americain.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw0rJfN_ZXE2WGXbwuVuARkJdQW_xHD2k',
    appId: '1:894004314968:ios:7d53bfb845198bab8ddb2d',
    messagingSenderId: '894004314968',
    projectId: 'huit-americain',
    storageBucket: 'huit-americain.firebasestorage.app',
    iosBundleId: 'com.example.huit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw0rJfN_ZXE2WGXbwuVuARkJdQW_xHD2k',
    appId: '1:894004314968:ios:7d53bfb845198bab8ddb2d',
    messagingSenderId: '894004314968',
    projectId: 'huit-americain',
    storageBucket: 'huit-americain.firebasestorage.app',
    iosBundleId: 'com.example.huit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsgBrxqgSCt83BxDHQyeScSAVRj7pwK7s',
    appId: '1:894004314968:web:3245dbb11a79f3388ddb2d',
    messagingSenderId: '894004314968',
    projectId: 'huit-americain',
    authDomain: 'huit-americain.firebaseapp.com',
    storageBucket: 'huit-americain.firebasestorage.app',
  );

}